spring:
  datasource:
    url: jdbc:h2:file:./bmsdata
    driverClassName: org.h2.Driver
    username: bmsadmin
    password: bmsadmin
    hikari:
      initialization-fail-timeout: 3600

    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api/v1

management:
  endpoint:
    health:
      enabled: true